### ISSUE TITLE
在哪里获取讲义的pdf文档

### ISSUE THREAD

**Issue by hisrg** [DroidAITech/ROS-Academy-for-Beginners#1]
请问在哪里获取讲义PDF之前，有时候https://github.com/DroidAITech/ROS-Academy-for-Beginners这里获取不到pdf文档

**Comment by sychaichangkun** [comment]
你好 在[https://www.gitbook.com/book/sychaichangkun/ros-tutorial-icourse163/details](https://www.gitbook.com/book/sychaichangkun/ros-tutorial-icourse163/details)   可以看到
