### ISSUE TITLE
编译demo时报错

### ISSUE THREAD

**Issue by 997931058** [DroidAITech/ROS-Academy-for-Beginners#10]
老师您好，我按照MOOC课程操作的时候，操作到编译github clone的代码的时候出现如下错误。之前的操作都和视频上您的一样，希望老师解答。

Traceback (most recent call last):
  File "/opt/ros/kinetic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 49, in <module>
    srv_template_map)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 213, in generate_from_command_line_options
    generate_from_file(argv[1], options.package, options.outdir, options.emdir, options.includepath, msg_template_dict, srv_template_dict)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 156, in generate_from_file
    _generate_srv_from_file(input_file, output_dir, template_dir, search_path, package_name, srv_template_dict, msg_template_dict)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 115, in _generate_srv_from_file
    search_path)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 77, in _generate_from_spec
    interpreter = em.Interpreter(output=ofile, globals=g, options={em.RAW_OPT:True,em.BUFFERED_OPT:True})
AttributeError: 'module' object has no attribute 'Interpreter'
ROS-Academy-for-Beginners/service_demo/CMakeFiles/service_demo_generate_messages_cpp.dir/build.make:63: recipe for target '/home/jason/aaa_ws/devel/include/service_demo/Greeting.h' failed
make[2]: *** [/home/jason/aaa_ws/devel/include/service_demo/Greeting.h] Error 1
make[2]: *** Deleting file '/home/jason/aaa_ws/devel/include/service_demo/Greeting.h'
CMakeFiles/Makefile2:1271: recipe for target 'ROS-Academy-for-Beginners/service_demo/CMakeFiles/service_demo_generate_messages_cpp.dir/all' failed
make[1]: *** [ROS-Academy-for-Beginners/service_demo/CMakeFiles/service_demo_generate_messages_cpp.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  2%] Built target service_demo_generate_messages_py
[  2%] Linking CXX executable /home/jason/aaa_ws/devel/lib/param_demo/param_demo
CMakeFiles/param_demo.dir/src/param_demo.cpp.o: In function `main':
param_demo.cpp:(.text+0x70): undefined reference to `ros::init(int&, char**, std::string const&, unsigned int)'
param_demo.cpp:(.text+0xcc): undefined reference to `ros::NodeHandle::NodeHandle(std::string const&, std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&)'
param_demo.cpp:(.text+0x12d): undefined reference to `ros::param::get(std::string const&, int&)'
param_demo.cpp:(.text+0x19b): undefined reference to `ros::NodeHandle::getParam(std::string const&, int&) const'
param_demo.cpp:(.text+0x2ae): undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
param_demo.cpp:(.text+0x3c8): undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
param_demo.cpp:(.text+0x4e2): undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
param_demo.cpp:(.text+0x5fc): undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
param_demo.cpp:(.text+0x6e0): undefined reference to `ros::NodeHandle::hasParam(std::string const&) const'
param_demo.cpp:(.text+0x774): undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
param_demo.cpp:(.text+0x88e): undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
param_demo.cpp:(.text+0x97a): undefined reference to `ros::param::set(std::string const&, int)'
param_demo.cpp:(.text+0x9eb): undefined reference to `ros::NodeHandle::setParam(std::string const&, int) const'
param_demo.cpp:(.text+0xa75): undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
param_demo.cpp:(.text+0xb85): undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
param_demo.cpp:(.text+0xc6c): undefined reference to `ros::NodeHandle::hasParam(std::string const&) const'
param_demo.cpp:(.text+0xcc9): undefined reference to `ros::param::has(std::string const&)'
param_demo.cpp:(.text+0xd66): undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
param_demo.cpp:(.text+0xe7d): undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
param_demo.cpp:(.text+0xf97): undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
param_demo.cpp:(.text+0x10ae): undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
param_demo.cpp:(.text+0x1192): undefined reference to `ros::NodeHandle::deleteParam(std::string const&) const'
param_demo.cpp:(.text+0x11ef): undefined reference to `ros::param::del(std::string const&)'
param_demo.cpp:(.text+0x128c): undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
param_demo.cpp:(.text+0x13a3): undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
param_demo.cpp:(.text+0x14bd): undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
param_demo.cpp:(.text+0x15d4): undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
param_demo.cpp:(.text+0x1718): undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
param_demo.cpp:(.text+0x17fc): undefined reference to `ros::param::get(std::string const&, int&)'
param_demo.cpp:(.text+0x1890): undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
param_demo.cpp:(.text+0x1979): undefined reference to `ros::param::get(std::string const&, int&)'
param_demo.cpp:(.text+0x1a0d): undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
param_demo.cpp:(.text+0x1af6): undefined reference to `ros::param::get(std::string const&, int&)'
param_demo.cpp:(.text+0x1b8a): undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
param_demo.cpp:(.text+0x1c73): undefined reference to `ros::param::get(std::string const&, int&)'
param_demo.cpp:(.text+0x1d07): undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
param_demo.cpp:(.text+0x1df0): undefined reference to `ros::param::get(std::string const&, int&)'
param_demo.cpp:(.text+0x1e84): undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
param_demo.cpp:(.text+0x1f6d): undefined reference to `ros::param::get(std::string const&, int&)'
param_demo.cpp:(.text+0x2001): undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
CMakeFiles/param_demo.dir/src/param_demo.cpp.o: In function `bool ros::NodeHandle::param<int>(std::string const&, int&, int const&) const':
param_demo.cpp:(.text._ZNK3ros10NodeHandle5paramIiEEbRKSsRT_RKS4_[_ZNK3ros10NodeHandle5paramIiEEbRKSsRT_RKS4_]+0x27): undefined reference to `ros::NodeHandle::hasParam(std::string const&) const'
param_demo.cpp:(.text._ZNK3ros10NodeHandle5paramIiEEbRKSsRT_RKS4_[_ZNK3ros10NodeHandle5paramIiEEbRKSsRT_RKS4_]+0x42): undefined reference to `ros::NodeHandle::getParam(std::string const&, int&) const'
collect2: error: ld returned 1 exit status
ROS-Academy-for-Beginners/param_demo/CMakeFiles/param_demo.dir/build.make:113: recipe for target '/home/jason/aaa_ws/devel/lib/param_demo/param_demo' failed
make[2]: *** [/home/jason/aaa_ws/devel/lib/param_demo/param_demo] Error 1
CMakeFiles/Makefile2:975: recipe for target 'ROS-Academy-for-Beginners/param_demo/CMakeFiles/param_demo.dir/all' failed
make[1]: *** [ROS-Academy-for-Beginners/param_demo/CMakeFiles/param_demo.dir/all] Error 2
[  2%] Linking CXX executable /home/jason/aaa_ws/devel/lib/tf_demo/Euler2Quaternion
CMakeFiles/Euler2Quaternion.dir/src/Euler2Quaternion.cpp.o: In function `tf::quaternionTFToMsg(tf::Quaternion const&, geometry_msgs::Quaternion_<std::allocator<void> >&)':
Euler2Quaternion.cpp:(.text+0xbb): undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
CMakeFiles/Euler2Quaternion.dir/src/Euler2Quaternion.cpp.o: In function `main':
Euler2Quaternion.cpp:(.text+0x3fb): undefined reference to `ros::init(int&, char**, std::string const&, unsigned int)'
Euler2Quaternion.cpp:(.text+0x457): undefined reference to `ros::NodeHandle::NodeHandle(std::string const&, std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&)'
collect2: error: ld returned 1 exit status
ROS-Academy-for-Beginners/tf_demo/CMakeFiles/Euler2Quaternion.dir/build.make:118: recipe for target '/home/jason/aaa_ws/devel/lib/tf_demo/Euler2Quaternion' failed
make[2]: *** [/home/jason/aaa_ws/devel/lib/tf_demo/Euler2Quaternion] Error 1
CMakeFiles/Makefile2:8098: recipe for target 'ROS-Academy-for-Beginners/tf_demo/CMakeFiles/Euler2Quaternion.dir/all' failed
make[1]: *** [ROS-Academy-for-Beginners/tf_demo/CMakeFiles/Euler2Quaternion.dir/all] Error 2
[  2%] Linking CXX executable /home/jason/aaa_ws/devel/lib/tf_demo/tf_listerner
[  3%] Linking CXX executable /home/jason/aaa_ws/devel/lib/tf_demo/Quaternion2Euler
CMakeFiles/tf_listerner.dir/src/tf_listerner.cpp.o: In function `main':
tf_listerner.cpp:(.text+0x76): undefined reference to `ros::init(int&, char**, std::string const&, unsigned int)'
tf_listerner.cpp:(.text+0xd2): undefined reference to `ros::NodeHandle::NodeHandle(std::string const&, std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&)'
tf_listerner.cpp:(.text+0x253): undefined reference to `tf::Transformer::waitForTransform(std::string const&, std::string const&, ros::Time const&, ros::Duration const&, ros::Duration const&, std::string*) const'
tf_listerner.cpp:(.text+0x39c): undefined reference to `tf::Transformer::lookupTransform(std::string const&, std::string const&, ros::Time const&, tf::StampedTransform&) const'
tf_listerner.cpp:(.text+0x8a8): undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
collect2: error: ld returned 1 exit status
ROS-Academy-for-Beginners/tf_demo/CMakeFiles/tf_listerner.dir/build.make:118: recipe for target '/home/jason/aaa_ws/devel/lib/tf_demo/tf_listerner' failed
make[2]: *** [/home/jason/aaa_ws/devel/lib/tf_demo/tf_listerner] Error 1
CMakeFiles/Makefile2:8209: recipe for target 'ROS-Academy-for-Beginners/tf_demo/CMakeFiles/tf_listerner.dir/all' failed
make[1]: *** [ROS-Academy-for-Beginners/tf_demo/CMakeFiles/tf_listerner.dir/all] Error 2
CMakeFiles/Quaternion2Euler.dir/src/Quaternion2Euler.cpp.o: In function `tf::quaternionMsgToTF(geometry_msgs::Quaternion_<std::allocator<void> > const&, tf::Quaternion&)':
Quaternion2Euler.cpp:(.text+0x109): undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
CMakeFiles/Quaternion2Euler.dir/src/Quaternion2Euler.cpp.o: In function `main':
Quaternion2Euler.cpp:(.text+0x269): undefined reference to `ros::init(int&, char**, std::string const&, unsigned int)'
Quaternion2Euler.cpp:(.text+0x2c5): undefined reference to `ros::NodeHandle::NodeHandle(std::string const&, std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&)'
collect2: error: ld returned 1 exit status
ROS-Academy-for-Beginners/tf_demo/CMakeFiles/Quaternion2Euler.dir/build.make:118: recipe for target '/home/jason/aaa_ws/devel/lib/tf_demo/Quaternion2Euler' failed
make[2]: *** [/home/jason/aaa_ws/devel/lib/tf_demo/Quaternion2Euler] Error 1
CMakeFiles/Makefile2:8172: recipe for target 'ROS-Academy-for-Beginners/tf_demo/CMakeFiles/Quaternion2Euler.dir/all' failed
make[1]: *** [ROS-Academy-for-Beginners/tf_demo/CMakeFiles/Quaternion2Euler.dir/all] Error 2
[  3%] Linking CXX executable /home/jason/aaa_ws/devel/lib/tf_demo/tf_broadcaster
[  4%] Linking CXX executable /home/jason/aaa_ws/devel/lib/tf_demo/coordinate_transformation
CMakeFiles/tf_broadcaster.dir/src/tf_broadcaster.cpp.o: In function `main':
tf_broadcaster.cpp:(.text+0x76): undefined reference to `ros::init(int&, char**, std::string const&, unsigned int)'
tf_broadcaster.cpp:(.text+0xd2): undefined reference to `ros::NodeHandle::NodeHandle(std::string const&, std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&)'
collect2: error: ld returned 1 exit status
ROS-Academy-for-Beginners/tf_demo/CMakeFiles/tf_broadcaster.dir/build.make:118: recipe for target '/home/jason/aaa_ws/devel/lib/tf_demo/tf_broadcaster' failed
make[2]: *** [/home/jason/aaa_ws/devel/lib/tf_demo/tf_broadcaster] Error 1
CMakeFiles/Makefile2:8061: recipe for target 'ROS-Academy-for-Beginners/tf_demo/CMakeFiles/tf_broadcaster.dir/all' failed
make[1]: *** [ROS-Academy-for-Beginners/tf_demo/CMakeFiles/tf_broadcaster.dir/all] Error 2
CMakeFiles/coordinate_transformation.dir/src/coordinate_transformation.cpp.o: In function `main':
coordinate_transformation.cpp:(.text+0x76): undefined reference to `ros::init(int&, char**, std::string const&, unsigned int)'
coordinate_transformation.cpp:(.text+0xd2): undefined reference to `ros::NodeHandle::NodeHandle(std::string const&, std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&)'
collect2: error: ld returned 1 exit status
ROS-Academy-for-Beginners/tf_demo/CMakeFiles/coordinate_transformation.dir/build.make:118: recipe for target '/home/jason/aaa_ws/devel/lib/tf_demo/coordinate_transformation' failed
make[2]: *** [/home/jason/aaa_ws/devel/lib/tf_demo/coordinate_transformation] Error 1
CMakeFiles/Makefile2:8135: recipe for target 'ROS-Academy-for-Beginners/tf_demo/CMakeFiles/coordinate_transformation.dir/all' failed
make[1]: *** [ROS-Academy-for-Beginners/tf_demo/CMakeFiles/coordinate_transformation.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j8 -l8" failed

**Comment by lazyparser** [comment]
Hi @likui1123 可以去 https://q.droid.ac.cn 去提问和讨论这个问题。我们已经转到Q站了

**Comment by lazyparser** [comment]
` AttributeError: 'module' object has no attribute 'Interpreter'`

错误的原因看起来在这里，可以从这个角度来搜索一下。
