### ISSUE TITLE
gazebo -v error

### ISSUE THREAD

**Issue by YunxiangLuo** [DroidAITech/ROS-Academy-for-Beginners#102]
gazebo: symbol lookup error: /usr/lib/x86_64-linux-gnu/libgazebo_common.so.9: undefined symbol: _ZN8ignition10fuel_tools12ClientConfig12SetUserAgentERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

**Comment by anchuanxu** [comment]
执行：`sudo apt-get update && upgrade`
