### ISSUE TITLE
关于源代码的修改

### ISSUE THREAD

**Issue by likui1123** [DroidAITech/ROS-Academy-for-Beginners#11]
l老师你好 我还是想问一下爱关于如何修改源代码的问题，在哪里可以获取全局局部路径规划的源代码呢，或者DWA之类的源代码，修改的如何放到ROS-Academy-for-Beginners下仿真呢 ，我看到ROS-Academy-for-Beginners下的文件都是一些参数文件不能找到算法的局部全局路径规划，amcl和dwa的算法

**Comment by sychaichangkun** [comment]
https://github.com/ros-planning/navigation
这里是ROS导航相关的源码，里面有局部和全局规划算法。
