### ISSUE TITLE
Ubuntu18.04中模型加载不出来

### ISSUE THREAD

**Issue by Sigmund-SJTUer** [DroidAITech/ROS-Academy-for-Beginners#137]
老师，我在ubuntu18.04中运行程序，gazebo模型出不来，只可以看到机器人的眼睛和轮子，控制程序也正常，是什么原因呢？怎么处理？
![2021-08-11](https://user-images.githubusercontent.com/79052189/129025893-bd6bc53c-204a-4ace-b597-8a94c922b686.png)

**Comment by YYYY1213800** [comment]
我也是，兄弟你解决了吗

**Comment by peitianyu** [comment]
请问解决了吗？我也遇到了

**Comment by Sigmund-SJTUer** [comment]
> 请问解决了吗？我也遇到了

虚拟机上跑仿真硬件加速不太好，下个双系统会加载出来。

**Comment by huiyue** [comment]
虚拟机没有解决办法吗？
