### ISSUE TITLE
caktin_make error[solved] undefined referenced to boost::system

### ISSUE THREAD

**Issue by Tabbleman** [DroidAITech/ROS-Academy-for-Beginners#154]
在对应的包里面的CMakeLists.txt中的加入`find_package(Boost REQUIRED COMPONENTS system`和在target_linked_libraries里面加入${Boost_LIBRARIES}[注意不是${Boost_LIBS}]

**Comment by ZhangHaHei** [comment]
请问这个课mooc还在吗？

**Comment by Tabbleman** [comment]
> 

还在，b战有

**Comment by ZhangHaHei** [comment]
谢谢啊，忘记b站也能看课了
