### ISSUE TITLE
关于您们做的博物馆模型

### ISSUE THREAD

**Issue by baldwinyang** [DroidAITech/ROS-Academy-for-Beginners#17]
我也想给实验室做一个模型 利用gazebo  crtl+b编辑了一个简单的模型 保存后会生成一个.config文件和一个.sdf文件 利用这个模型模仿你们的.world 文件写了一个world模型 但是打开是空的 请问您们是怎么做的呢?一个大概就行  谢谢

**Comment by seanXMU** [comment]
请问您是怎么解决的呢
