### ISSUE TITLE
Are those packages availabe for all ROS versions?

### ISSUE THREAD

**Issue by ChurchKing** [DroidAITech/ROS-Academy-for-Beginners#2]
some complicated problems occuured while running  [Robot_sim_demo] package on Ros Indigo,  are those packages available on the previous ROS versions like indigo?

Thx

**Comment by sychaichangkun** [comment]
Can you paste a screenshot of the errors?
Did't run on Indigo before, But I would try to fix the bugs.

**Comment by Acmece** [comment]
I think it is probably impossible.(ROS Indigo)
Here is the error when I install the dependency:
```
acmece@acmece:~/tutorial_ws$ rosdep install --from-paths src --ignore-src --rosdistro=kinetic -y
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
robot_sim_demo: No definition of [yocs_cmd_vel_mux] for OS version [trusty]
navigation_sim_demo: No definition of [dwa_local_planner] for OS version [trusty]
slam_sim_demo: No definition of [hector_mapping] for OS version [trusty]
```

**Comment by yowlings** [comment]
目前支持稳定运行的ROS版本为indigo及以后。
