### ISSUE TITLE
catkin_make时出错

### ISSUE THREAD

**Issue by B0Njour** [DroidAITech/ROS-Academy-for-Beginners#22]
-- +++ processing catkin metapackage: 'ros_academy_for_beginners'
-- ==> add_subdirectory(ROS-Academy-for-Beginners/ros_academy_for_beginners)
-- +++ processing catkin package: 'test1'
-- ==> add_subdirectory(test1)
-- +++ processing catkin package: 'orbslam2_demo'
-- ==> add_subdirectory(ROS-Academy-for-Beginners/orbslam2_demo)
-- +++ processing catkin package: 'param_demo'
-- ==> add_subdirectory(ROS-Academy-for-Beginners/param_demo)
-- +++ processing catkin package: 'rtabmap_demo'
-- ==> add_subdirectory(ROS-Academy-for-Beginners/rtabmap_demo)
-- +++ processing catkin package: 'service_demo'
-- ==> add_subdirectory(ROS-Academy-for-Beginners/service_demo)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- service_demo: 0 messages, 1 services
-- +++ processing catkin package: 'test2'
-- ==> add_subdirectory(test2)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- +++ processing catkin package: 'topic_demo'
-- ==> add_subdirectory(ROS-Academy-for-Beginners/topic_demo)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- topic_demo: 1 messages, 0 services
-- +++ processing catkin package: 'action_demo'
-- ==> add_subdirectory(ROS-Academy-for-Beginners/action_demo)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
-- Generating .msg files for action action_demo/DoDishes /home/bonjour/catkin_ws/src/ROS-Academy-for-Beginners/action_demo/action/DoDishes.action
-- action_demo: 7 messages, 0 services
-- +++ processing catkin package: 'msgs_demo'
-- ==> add_subdirectory(ROS-Academy-for-Beginners/msgs_demo)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- Generating .msg files for action msgs_demo/AutoDocking /home/bonjour/catkin_ws/src/ROS-Academy-for-Beginners/msgs_demo/action/AutoDocking.action
-- Generating .msg files for action msgs_demo/AddTwoInts /home/bonjour/catkin_ws/src/ROS-Academy-for-Beginners/msgs_demo/action/AddTwoInts.action
-- Generating .msg files for action msgs_demo/GetMap /home/bonjour/catkin_ws/src/ROS-Academy-for-Beginners/msgs_demo/action/GetMap.action
-- Generating .msg files for action msgs_demo/MoveBase /home/bonjour/catkin_ws/src/ROS-Academy-for-Beginners/msgs_demo/action/MoveBase.action
-- msgs_demo: 42 messages, 9 services
-- +++ processing catkin package: 'navigation_sim_demo'
-- ==> add_subdirectory(ROS-Academy-for-Beginners/navigation_sim_demo)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- +++ processing catkin package: 'robot_sim_demo'
-- ==> add_subdirectory(ROS-Academy-for-Beginners/robot_sim_demo)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- +++ processing catkin package: 'slam_sim_demo'
-- ==> add_subdirectory(ROS-Academy-for-Beginners/slam_sim_demo)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- +++ processing catkin package: 'tf_demo'
-- ==> add_subdirectory(ROS-Academy-for-Beginners/tf_demo)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- +++ processing catkin package: 'tf_follower'
-- ==> add_subdirectory(ROS-Academy-for-Beginners/tf_follower)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- +++ processing catkin package: 'urdf_demo'
-- ==> add_subdirectory(ROS-Academy-for-Beginners/urdf_demo)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- Configuring done
-- Generating done
-- Build files have been written to: /home/bonjour/catkin_ws/build
####
####
Scanning dependencies of target param_demo
[  0%] Built target std_msgs_generate_messages_py
[  0%] Built target roscpp_generate_messages_py
[  0%] Building CXX object ROS-Academy-for-Beginners/param_demo/CMakeFiles/param_demo.dir/src/param_demo.cpp.o
[  0%] Built target rosgraph_msgs_generate_messages_eus
[  0%] Built target rosgraph_msgs_generate_messages_nodejs
[  0%] Built target roscpp_generate_messages_cpp
[  0%] Built target rosgraph_msgs_generate_messages_cpp
[  0%] Built target _service_demo_generate_messages_check_deps_Greeting
[  0%] Built target std_msgs_generate_messages_cpp
[  0%] Built target roscpp_generate_messages_eus
[  0%] Built target rosgraph_msgs_generate_messages_py
[  0%] Built target rosgraph_msgs_generate_messages_lisp
[  0%] Built target roscpp_generate_messages_nodejs
[  0%] Built target std_msgs_generate_messages_nodejs
[  0%] Built target roscpp_generate_messages_lisp
[  0%] Built target std_msgs_generate_messages_eus
[  0%] Built target std_msgs_generate_messages_lisp
[  1%] Built target service_demo_generate_messages_py
[  1%] Generating C++ code from service_demo/Greeting.srv
[  1%] Built target service_demo_generate_messages_lisp
[  2%] Built target service_demo_generate_messages_eus
Traceback (most recent call last):
  File "/opt/ros/kinetic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 41, in <module>
    import genmsg.template_tools
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 39, in <module>
    import em
ModuleNotFoundError: No module named 'em'
ROS-Academy-for-Beginners/service_demo/CMakeFiles/service_demo_generate_messages_cpp.dir/build.make:63: recipe for target '/home/bonjour/catkin_ws/devel/include/service_demo/Greeting.h' failed
make[2]: *** [/home/bonjour/catkin_ws/devel/include/service_demo/Greeting.h] Error 1
CMakeFiles/Makefile2:1289: recipe for target 'ROS-Academy-for-Beginners/service_demo/CMakeFiles/service_demo_generate_messages_cpp.dir/all' failed
make[1]: *** [ROS-Academy-for-Beginners/service_demo/CMakeFiles/service_demo_generate_messages_cpp.dir/all] Error 2
make[1]: *** 正在等待未完成的任务....
[  2%] Built target _topic_demo_generate_messages_check_deps_gps
[  2%] Built target _action_demo_generate_messages_check_deps_DoDishesResult
[  2%] Linking CXX executable /home/bonjour/catkin_ws/devel/lib/param_demo/param_demo
[  2%] Built target param_demo
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j4 -l4" failed

请求老师指教～～

**Comment by sychaichangkun** [comment]
试试这个帖子的方法
https://answers.ros.org/question/257331/python-module-empy-missing-tutorials/
