### ISSUE TITLE
catkin_make时出错

### ISSUE THREAD

**Issue by KeMoing** [DroidAITech/ROS-Academy-for-Beginners#34]
Base path: /home/xwj/catkin_ws
Source space: /home/xwj/catkin_ws/src
Build space: /home/xwj/catkin_ws/build
Devel space: /home/xwj/catkin_ws/devel
Install space: /home/xwj/catkin_ws/install
####
####
-- Using CATKIN_DEVEL_PREFIX: /home/xwj/catkin_ws/devel
-- Using CMAKE_PREFIX_PATH: /home/xwj/catkin_ws/devel;/opt/ros/kinetic
-- This workspace overlays: /home/xwj/catkin_ws/devel;/opt/ros/kinetic
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/xwj/catkin_ws/build/test_results
-- Found gmock sources under '/usr/src/gmock': gmock will be built
-- Found gtest sources under '/usr/src/gmock': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.7.14
-- BUILD_SHARED_LIBS is on
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 36 packages in topological order:
-- ~~  - rbx1 (metapackage)
-- ~~  - ros_academy_for_beginners (metapackage)
-- ~~  - turtlebot3 (metapackage)
-- ~~  - turtlebot3_msgs
-- ~~  - turtlebot3_navigation
-- ~~  - beginner_tutorials
-- ~~  - orbslam2_demo
-- ~~  - param_demo
-- ~~  - rbx1_speech
-- ~~  - rtabmap_demo
-- ~~  - service_demo
-- ~~  - test
-- ~~  - topic_demo
-- ~~  - action_demo
-- ~~  - msgs_demo
-- ~~  - rbx1_bringup
-- ~~  - rbx1_dynamixels
-- ~~  - rbx1_vision
-- ~~  - rplidar_ros
-- ~~  - navigation_sim_demo
-- ~~  - rbx1_apps
-- ~~  - rbx1_nav
-- ~~  - rf2o_laser_odometry
-- ~~  - robot_setup_tf
-- ~~  - robot_sim_demo
-- ~~  - slam_sim_demo
-- ~~  - tf_demo
-- ~~  - tf_follower
-- ~~  - turtlebot3_bringup
-- ~~  - turtlebot3_example
-- ~~  - turtlebot3_slam
-- ~~  - turtlebot3_teleop
-- ~~  - learning_tf
-- ~~  - rbx1_description
-- ~~  - urdf_demo
-- ~~  - turtlebot3_description
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin metapackage: 'rbx1'
-- ==> add_subdirectory(rbx1/rbx1)
-- +++ processing catkin metapackage: 'ros_academy_for_beginners'
-- ==> add_subdirectory(ROS-Academy-for-Beginners/ros_academy_for_beginners)
-- +++ processing catkin metapackage: 'turtlebot3'
-- ==> add_subdirectory(turtlebot3/turtlebot3)
-- +++ processing catkin package: 'turtlebot3_msgs'
-- ==> add_subdirectory(turtlebot3_msgs)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- turtlebot3_msgs: 3 messages, 0 services
-- +++ processing catkin package: 'turtlebot3_navigation'
-- ==> add_subdirectory(turtlebot3/turtlebot3_navigation)
-- +++ processing catkin package: 'beginner_tutorials'
-- ==> add_subdirectory(beginner_tutorials)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- beginner_tutorials: 1 messages, 1 services
-- +++ processing catkin package: 'orbslam2_demo'
-- ==> add_subdirectory(ROS-Academy-for-Beginners/orbslam2_demo)
-- +++ processing catkin package: 'param_demo'
-- ==> add_subdirectory(ROS-Academy-for-Beginners/param_demo)
-- +++ processing catkin package: 'rbx1_speech'
-- ==> add_subdirectory(rbx1/rbx1_speech)
-- +++ processing catkin package: 'rtabmap_demo'
-- ==> add_subdirectory(ROS-Academy-for-Beginners/rtabmap_demo)
-- +++ processing catkin package: 'service_demo'
-- ==> add_subdirectory(ROS-Academy-for-Beginners/service_demo)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- service_demo: 0 messages, 1 services
-- +++ processing catkin package: 'test'
-- ==> add_subdirectory(test)
-- +++ processing catkin package: 'topic_demo'
-- ==> add_subdirectory(ROS-Academy-for-Beginners/topic_demo)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- topic_demo: 1 messages, 0 services
CMake Error at ROS-Academy-for-Beginners/topic_demo/CMakeLists.txt:154 (add_executable):
  add_executable cannot create target "talker" because another target with
  the same name already exists.  The existing target is an executable created
  in source directory "/home/xwj/catkin_ws/src/beginner_tutorials".  See
  documentation for policy CMP0002 for more details.

CMake Error at ROS-Academy-for-Beginners/topic_demo/CMakeLists.txt:157 (target_link_libraries):
  Attempt to add link library "/opt/ros/kinetic/lib/libroscpp.so" to target
  "talker" which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/topic_demo/CMakeLists.txt:157 (target_link_libraries):
  Attempt to add link library
  "/usr/lib/x86_64-linux-gnu/libboost_filesystem.so" to target "talker" which
  is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/topic_demo/CMakeLists.txt:157 (target_link_libraries):
  Attempt to add link library "/usr/lib/x86_64-linux-gnu/libboost_signals.so"
  to target "talker" which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/topic_demo/CMakeLists.txt:157 (target_link_libraries):
  Attempt to add link library "/opt/ros/kinetic/lib/librosconsole.so" to
  target "talker" which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/topic_demo/CMakeLists.txt:157 (target_link_libraries):
  Attempt to add link library "/opt/ros/kinetic/lib/librosconsole_log4cxx.so"
  to target "talker" which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/topic_demo/CMakeLists.txt:157 (target_link_libraries):
  Attempt to add link library
  "/opt/ros/kinetic/lib/librosconsole_backend_interface.so" to target
  "talker" which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/topic_demo/CMakeLists.txt:157 (target_link_libraries):
  Attempt to add link library "/usr/lib/x86_64-linux-gnu/liblog4cxx.so" to
  target "talker" which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/topic_demo/CMakeLists.txt:157 (target_link_libraries):
  Attempt to add link library "/usr/lib/x86_64-linux-gnu/libboost_regex.so"
  to target "talker" which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/topic_demo/CMakeLists.txt:157 (target_link_libraries):
  Attempt to add link library "/opt/ros/kinetic/lib/libxmlrpcpp.so" to target
  "talker" which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/topic_demo/CMakeLists.txt:157 (target_link_libraries):
  Attempt to add link library
  "/opt/ros/kinetic/lib/libroscpp_serialization.so" to target "talker" which
  is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/topic_demo/CMakeLists.txt:157 (target_link_libraries):
  Attempt to add link library "/opt/ros/kinetic/lib/librostime.so" to target
  "talker" which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/topic_demo/CMakeLists.txt:157 (target_link_libraries):
  Attempt to add link library "/opt/ros/kinetic/lib/libcpp_common.so" to
  target "talker" which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/topic_demo/CMakeLists.txt:157 (target_link_libraries):
  Attempt to add link library "/usr/lib/x86_64-linux-gnu/libboost_system.so"
  to target "talker" which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/topic_demo/CMakeLists.txt:157 (target_link_libraries):
  Attempt to add link library "/usr/lib/x86_64-linux-gnu/libboost_thread.so"
  to target "talker" which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/topic_demo/CMakeLists.txt:157 (target_link_libraries):
  Attempt to add link library "/usr/lib/x86_64-linux-gnu/libboost_chrono.so"
  to target "talker" which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/topic_demo/CMakeLists.txt:157 (target_link_libraries):
  Attempt to add link library
  "/usr/lib/x86_64-linux-gnu/libboost_date_time.so" to target "talker" which
  is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/topic_demo/CMakeLists.txt:157 (target_link_libraries):
  Attempt to add link library "/usr/lib/x86_64-linux-gnu/libboost_atomic.so"
  to target "talker" which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/topic_demo/CMakeLists.txt:157 (target_link_libraries):
  Attempt to add link library "/usr/lib/x86_64-linux-gnu/libpthread.so" to
  target "talker" which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/topic_demo/CMakeLists.txt:157 (target_link_libraries):
  Attempt to add link library
  "/usr/lib/x86_64-linux-gnu/libconsole_bridge.so" to target "talker" which
  is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/topic_demo/CMakeLists.txt:159 (add_executable):
  add_executable cannot create target "listener" because another target with
  the same name already exists.  The existing target is an executable created
  in source directory "/home/xwj/catkin_ws/src/beginner_tutorials".  See
  documentation for policy CMP0002 for more details.

CMake Error at ROS-Academy-for-Beginners/topic_demo/CMakeLists.txt:161 (target_link_libraries):
  Attempt to add link library "/opt/ros/kinetic/lib/libroscpp.so" to target
  "listener" which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/topic_demo/CMakeLists.txt:161 (target_link_libraries):
  Attempt to add link library
  "/usr/lib/x86_64-linux-gnu/libboost_filesystem.so" to target "listener"
  which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/topic_demo/CMakeLists.txt:161 (target_link_libraries):
  Attempt to add link library "/usr/lib/x86_64-linux-gnu/libboost_signals.so"
  to target "listener" which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/topic_demo/CMakeLists.txt:161 (target_link_libraries):
  Attempt to add link library "/opt/ros/kinetic/lib/librosconsole.so" to
  target "listener" which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/topic_demo/CMakeLists.txt:161 (target_link_libraries):
  Attempt to add link library "/opt/ros/kinetic/lib/librosconsole_log4cxx.so"
  to target "listener" which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/topic_demo/CMakeLists.txt:161 (target_link_libraries):
  Attempt to add link library
  "/opt/ros/kinetic/lib/librosconsole_backend_interface.so" to target
  "listener" which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/topic_demo/CMakeLists.txt:161 (target_link_libraries):
  Attempt to add link library "/usr/lib/x86_64-linux-gnu/liblog4cxx.so" to
  target "listener" which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/topic_demo/CMakeLists.txt:161 (target_link_libraries):
  Attempt to add link library "/usr/lib/x86_64-linux-gnu/libboost_regex.so"
  to target "listener" which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/topic_demo/CMakeLists.txt:161 (target_link_libraries):
  Attempt to add link library "/opt/ros/kinetic/lib/libxmlrpcpp.so" to target
  "listener" which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/topic_demo/CMakeLists.txt:161 (target_link_libraries):
  Attempt to add link library
  "/opt/ros/kinetic/lib/libroscpp_serialization.so" to target "listener"
  which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/topic_demo/CMakeLists.txt:161 (target_link_libraries):
  Attempt to add link library "/opt/ros/kinetic/lib/librostime.so" to target
  "listener" which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/topic_demo/CMakeLists.txt:161 (target_link_libraries):
  Attempt to add link library "/opt/ros/kinetic/lib/libcpp_common.so" to
  target "listener" which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/topic_demo/CMakeLists.txt:161 (target_link_libraries):
  Attempt to add link library "/usr/lib/x86_64-linux-gnu/libboost_system.so"
  to target "listener" which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/topic_demo/CMakeLists.txt:161 (target_link_libraries):
  Attempt to add link library "/usr/lib/x86_64-linux-gnu/libboost_thread.so"
  to target "listener" which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/topic_demo/CMakeLists.txt:161 (target_link_libraries):
  Attempt to add link library "/usr/lib/x86_64-linux-gnu/libboost_chrono.so"
  to target "listener" which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/topic_demo/CMakeLists.txt:161 (target_link_libraries):
  Attempt to add link library
  "/usr/lib/x86_64-linux-gnu/libboost_date_time.so" to target "listener"
  which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/topic_demo/CMakeLists.txt:161 (target_link_libraries):
  Attempt to add link library "/usr/lib/x86_64-linux-gnu/libboost_atomic.so"
  to target "listener" which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/topic_demo/CMakeLists.txt:161 (target_link_libraries):
  Attempt to add link library "/usr/lib/x86_64-linux-gnu/libpthread.so" to
  target "listener" which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/topic_demo/CMakeLists.txt:161 (target_link_libraries):
  Attempt to add link library
  "/usr/lib/x86_64-linux-gnu/libconsole_bridge.so" to target "listener" which
  is not built in this directory.

-- +++ processing catkin package: 'action_demo'
-- ==> add_subdirectory(ROS-Academy-for-Beginners/action_demo)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
-- Generating .msg files for action action_demo/DoDishes /home/xwj/catkin_ws/src/ROS-Academy-for-Beginners/action_demo/action/DoDishes.action
-- action_demo: 7 messages, 0 services
-- +++ processing catkin package: 'msgs_demo'
-- ==> add_subdirectory(ROS-Academy-for-Beginners/msgs_demo)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- Generating .msg files for action msgs_demo/AutoDocking /home/xwj/catkin_ws/src/ROS-Academy-for-Beginners/msgs_demo/action/AutoDocking.action
-- Generating .msg files for action msgs_demo/AddTwoInts /home/xwj/catkin_ws/src/ROS-Academy-for-Beginners/msgs_demo/action/AddTwoInts.action
-- Generating .msg files for action msgs_demo/GetMap /home/xwj/catkin_ws/src/ROS-Academy-for-Beginners/msgs_demo/action/GetMap.action
-- Generating .msg files for action msgs_demo/MoveBase /home/xwj/catkin_ws/src/ROS-Academy-for-Beginners/msgs_demo/action/MoveBase.action
-- msgs_demo: 42 messages, 9 services
-- +++ processing catkin package: 'rbx1_bringup'
-- ==> add_subdirectory(rbx1/rbx1_bringup)
-- +++ processing catkin package: 'rbx1_dynamixels'
-- ==> add_subdirectory(rbx1/rbx1_dynamixels)
-- +++ processing catkin package: 'rbx1_vision'
-- ==> add_subdirectory(rbx1/rbx1_vision)
-- +++ processing catkin package: 'rplidar_ros'
-- ==> add_subdirectory(rplidar_ros)
-- +++ processing catkin package: 'navigation_sim_demo'
-- ==> add_subdirectory(ROS-Academy-for-Beginners/navigation_sim_demo)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- +++ processing catkin package: 'rbx1_apps'
-- ==> add_subdirectory(rbx1/rbx1_apps)
-- +++ processing catkin package: 'rbx1_nav'
-- ==> add_subdirectory(rbx1/rbx1_nav)
-- +++ processing catkin package: 'rf2o_laser_odometry'
-- ==> add_subdirectory(rf2o_laser_odometry)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
-- +++ processing catkin package: 'robot_setup_tf'
-- ==> add_subdirectory(robot_setup_tf)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- +++ processing catkin package: 'robot_sim_demo'
-- ==> add_subdirectory(ROS-Academy-for-Beginners/robot_sim_demo)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- +++ processing catkin package: 'slam_sim_demo'
-- ==> add_subdirectory(ROS-Academy-for-Beginners/slam_sim_demo)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- +++ processing catkin package: 'tf_demo'
-- ==> add_subdirectory(ROS-Academy-for-Beginners/tf_demo)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
CMake Error at ROS-Academy-for-Beginners/tf_demo/CMakeLists.txt:130 (add_executable):
  add_executable cannot create target "tf_broadcaster" because another target
  with the same name already exists.  The existing target is an executable
  created in source directory "/home/xwj/catkin_ws/src/robot_setup_tf".  See
  documentation for policy CMP0002 for more details.

CMake Error at ROS-Academy-for-Beginners/tf_demo/CMakeLists.txt:146 (target_link_libraries):
  Attempt to add link library "/opt/ros/kinetic/lib/libtf.so" to target
  "tf_broadcaster" which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/tf_demo/CMakeLists.txt:146 (target_link_libraries):
  Attempt to add link library "/opt/ros/kinetic/lib/libtf2_ros.so" to target
  "tf_broadcaster" which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/tf_demo/CMakeLists.txt:146 (target_link_libraries):
  Attempt to add link library "/opt/ros/kinetic/lib/libactionlib.so" to
  target "tf_broadcaster" which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/tf_demo/CMakeLists.txt:146 (target_link_libraries):
  Attempt to add link library "/opt/ros/kinetic/lib/libmessage_filters.so" to
  target "tf_broadcaster" which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/tf_demo/CMakeLists.txt:146 (target_link_libraries):
  Attempt to add link library "/opt/ros/kinetic/lib/libroscpp.so" to target
  "tf_broadcaster" which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/tf_demo/CMakeLists.txt:146 (target_link_libraries):
  Attempt to add link library
  "/usr/lib/x86_64-linux-gnu/libboost_filesystem.so" to target
  "tf_broadcaster" which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/tf_demo/CMakeLists.txt:146 (target_link_libraries):
  Attempt to add link library "/usr/lib/x86_64-linux-gnu/libboost_signals.so"
  to target "tf_broadcaster" which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/tf_demo/CMakeLists.txt:146 (target_link_libraries):
  Attempt to add link library "/opt/ros/kinetic/lib/libxmlrpcpp.so" to target
  "tf_broadcaster" which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/tf_demo/CMakeLists.txt:146 (target_link_libraries):
  Attempt to add link library "/opt/ros/kinetic/lib/libtf2.so" to target
  "tf_broadcaster" which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/tf_demo/CMakeLists.txt:146 (target_link_libraries):
  Attempt to add link library "/opt/ros/kinetic/lib/librosconsole.so" to
  target "tf_broadcaster" which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/tf_demo/CMakeLists.txt:146 (target_link_libraries):
  Attempt to add link library "/opt/ros/kinetic/lib/librosconsole_log4cxx.so"
  to target "tf_broadcaster" which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/tf_demo/CMakeLists.txt:146 (target_link_libraries):
  Attempt to add link library
  "/opt/ros/kinetic/lib/librosconsole_backend_interface.so" to target
  "tf_broadcaster" which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/tf_demo/CMakeLists.txt:146 (target_link_libraries):
  Attempt to add link library "/usr/lib/x86_64-linux-gnu/liblog4cxx.so" to
  target "tf_broadcaster" which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/tf_demo/CMakeLists.txt:146 (target_link_libraries):
  Attempt to add link library "/usr/lib/x86_64-linux-gnu/libboost_regex.so"
  to target "tf_broadcaster" which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/tf_demo/CMakeLists.txt:146 (target_link_libraries):
  Attempt to add link library
  "/opt/ros/kinetic/lib/libroscpp_serialization.so" to target
  "tf_broadcaster" which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/tf_demo/CMakeLists.txt:146 (target_link_libraries):
  Attempt to add link library "/opt/ros/kinetic/lib/librostime.so" to target
  "tf_broadcaster" which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/tf_demo/CMakeLists.txt:146 (target_link_libraries):
  Attempt to add link library "/opt/ros/kinetic/lib/libcpp_common.so" to
  target "tf_broadcaster" which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/tf_demo/CMakeLists.txt:146 (target_link_libraries):
  Attempt to add link library "/usr/lib/x86_64-linux-gnu/libboost_system.so"
  to target "tf_broadcaster" which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/tf_demo/CMakeLists.txt:146 (target_link_libraries):
  Attempt to add link library "/usr/lib/x86_64-linux-gnu/libboost_thread.so"
  to target "tf_broadcaster" which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/tf_demo/CMakeLists.txt:146 (target_link_libraries):
  Attempt to add link library "/usr/lib/x86_64-linux-gnu/libboost_chrono.so"
  to target "tf_broadcaster" which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/tf_demo/CMakeLists.txt:146 (target_link_libraries):
  Attempt to add link library
  "/usr/lib/x86_64-linux-gnu/libboost_date_time.so" to target
  "tf_broadcaster" which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/tf_demo/CMakeLists.txt:146 (target_link_libraries):
  Attempt to add link library "/usr/lib/x86_64-linux-gnu/libboost_atomic.so"
  to target "tf_broadcaster" which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/tf_demo/CMakeLists.txt:146 (target_link_libraries):
  Attempt to add link library "/usr/lib/x86_64-linux-gnu/libpthread.so" to
  target "tf_broadcaster" which is not built in this directory.

CMake Error at ROS-Academy-for-Beginners/tf_demo/CMakeLists.txt:146 (target_link_libraries):
  Attempt to add link library
  "/usr/lib/x86_64-linux-gnu/libconsole_bridge.so" to target "tf_broadcaster"
  which is not built in this directory.

-- +++ processing catkin package: 'tf_follower'
-- ==> add_subdirectory(ROS-Academy-for-Beginners/tf_follower)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- +++ processing catkin package: 'turtlebot3_bringup'
-- ==> add_subdirectory(turtlebot3/turtlebot3_bringup)
-- +++ processing catkin package: 'turtlebot3_example'
-- ==> add_subdirectory(turtlebot3/turtlebot3_example)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- Generating .msg files for action turtlebot3_example/Turtlebot3 /home/xwj/catkin_ws/src/turtlebot3/turtlebot3_example/action/Turtlebot3.action
-- turtlebot3_example: 7 messages, 0 services
-- +++ processing catkin package: 'turtlebot3_slam'
-- ==> add_subdirectory(turtlebot3/turtlebot3_slam)
-- +++ processing catkin package: 'turtlebot3_teleop'
-- ==> add_subdirectory(turtlebot3/turtlebot3_teleop)
-- +++ processing catkin package: 'learning_tf'
-- ==> add_subdirectory(learning_tf)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- +++ processing catkin package: 'rbx1_description'
-- ==> add_subdirectory(rbx1/rbx1_description)
-- +++ processing catkin package: 'urdf_demo'
-- ==> add_subdirectory(ROS-Academy-for-Beginners/urdf_demo)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- +++ processing catkin package: 'turtlebot3_description'
-- ==> add_subdirectory(turtlebot3/turtlebot3_description)
-- Configuring incomplete, errors occurred!
See also "/home/xwj/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/xwj/catkin_ws/build/CMakeFiles/CMakeError.log".
Makefile:2292: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 1
Invoking "make cmake_check_build_system" failed

**Comment by sychaichangkun** [comment]
目标文件重名了，把有重名的包删掉

CMake Error at ROS-Academy-for-Beginners/topic_demo/CMakeLists.txt:154 (add_executable):
add_executable cannot create target "talker" because another target with
the same name already exists. The existing target is an executable created
in source directory "/home/xwj/catkin_ws/src/beginner_tutorials
