### ISSUE TITLE
在Melodic上安装依赖时出现的问题该怎么解决

### ISSUE THREAD

**Issue by palacexu** [DroidAITech/ROS-Academy-for-Beginners#41]
环境是Ubuntu18.04，ros Melodic，将ROS-Academy-for-Beginners克隆到src后，再在catkin_ws中安装依赖时出现了以下问题

`abc@ubuntu:~/catkin_ws$ rosdep install --from-paths src --ignore-src --rosdistro=melodic -y
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
navigation_sim_demo: Cannot locate rosdep definition for [gmapping]
slam_sim_demo: Cannot locate rosdep definition for [hector_mapping]
`

![capture_20190601203740770](https://user-images.githubusercontent.com/48762963/58749116-36360380-84b4-11e9-8a6f-33987b959585.jpg)

**Comment by sychaichangkun** [comment]
建议用ubuntu16.04+kinetic版本
melodic版本的一些软件包 官方还没有发布

http://answers.ros.org/question/296170/melodic-gmapping/
