### ISSUE TITLE
Zdzn.yaml里面的参数是对应相机模型的吗？

### ISSUE THREAD

**Issue by why-freedom** [DroidAITech/ROS-Academy-for-Beginners#42]
您好。学习了ros课程，我有以下疑问：
一、我在此仿真环境下跑ORBSLAM2误差都在1-5米以上，我觉得是参数文件设置问题和一部分环境问题。这个yaml文件是对应里面相机文件的真实参数吧？
二、在跑orbslam2时相机坐标应该和里程计坐标系转换过了吧？那视觉里程计和轮式里程计最终绝对位姿应该是接近重合吧？
谢谢

**Comment by sychaichangkun** [comment]
1. Zdzn.yaml只是一个演示的配置，不一定是仿真模型里的参数

2. 应该是做了转化，如果视觉里程计调参的效果足够精确，应该和轮式的差不多的

**Comment by Y-pandaman** [comment]
> 您好。学习了ros课程，我有以下疑问：
> 一、我在此仿真环境下跑ORBSLAM2误差都在1-5米以上，我觉得是参数文件设置问题和一部分环境问题。这个yaml文件是对应里面相机文件的真实参数吧？
> 二、在跑orbslam2时相机坐标应该和里程计坐标系转换过了吧？那视觉里程计和轮式里程计最终绝对位姿应该是接近重合吧？
> 谢谢

你好，我跑了ORB_SLAM2，轨迹飘得很厉害，机器人原地旋转轨迹都会变化很大，请问你出现过这种情况吗？

**Comment by kanglang123** [comment]
我跑ORB_SLAM2，相机内参用Zdzn.yaml，在稀疏点云图中，相机的轨迹根本跟踪不上。
