### ISSUE TITLE
老师好，我把laserscan添加到rviz中，并且将topic设定为/scan但是得不到雷达数据的图像

### ISSUE THREAD

**Issue by JinTongxing** [DroidAITech/ROS-Academy-for-Beginners#5]
gazebo已经更新到最新版本
使用rostopic info /scan看到该节点确实被rviz订阅了
把camera, pointcloud添加到rviz中显示是正常的
刚刚用rostopic echo看了看，ranges全部是-inf, intensities全部是1.0，应该是数据有问题？该怎么办呢？
谢谢

**Comment by JinTongxing** [comment]
已经解决了

**Comment by turboxin** [comment]
可以请问下你是怎么解决的吗，我也碰到这个问题了。谢谢！

**Comment by hdongdong123** [comment]
我也遇到这个问题了，直接用 rostopic echo /scan接受到的数据全是inf

**Comment by ShelyH** [comment]
您好，请问你是怎么解决的，我也遇到了这个问题
