### ISSUE TITLE
你好，我在克隆这个包的时候遇到了问题，下载没有问题，在安装的时候报错了

### ISSUE THREAD

**Issue by HoodguyKevin** [DroidAITech/ROS-Academy-for-Beginners#58]
ganyuqiu1997@ganyuqiu1997:~/catkin_ws$ rosdep install --from-paths src --ignore-src --rosdistro=kinetic -y
Traceback (most recent call last):
  File "/usr/bin/rosdep", line 3, in <module>
    from rosdep2.main import rosdep_main
ImportError: No module named 'rosdep2'
请问是哪里错误了？谢谢

**Comment by sychaichangkun** [comment]
你的rosdep可能没有装全
试试sudo apt-get install python-rosdep
