### ISSUE TITLE
如果想正确操作sim中的机器人至少要安装以下依赖。

### ISSUE THREAD

**Issue by kkkkkaiai** [DroidAITech/ROS-Academy-for-Beginners#62]
sudo apt install ros-kinetic-controller-manager
sudo apt install ros-kinetic-move-base 
sudo apt install ros-kinetic-map-server
sudo apt install ros-kinetic-amcl
sudo apt install ros-kinetic-gmapping
sudo apt install ros-kinetic-dwa-local-planner
sudo apt install ros-kinetic-slam-karto 
sudo apt install ros-kinetic-hector-mapping

sudo apt-get install ros-kinetic-controller-interface
sudo apt-get install ros-kinetic-gazebo-ros-control
sudo apt install ros-kinetic-joint-state-controller
sudo apt-get install ros-kinetic-navigation  
sudo apt install ros-kinetic-yocs-cmd-vel-mux
sudo apt install ros-kinetic-effort-controllers

**Comment by anchuanxu** [comment]
确定正确按照README上述说执行:

rosdep install --from-paths src --ignore-src --rosdistro=kinetic -y 了吗
