### ISSUE TITLE
运行调用机器人摄像头画面时报错

### ISSUE THREAD

**Issue by x7hkvip** [DroidAITech/ROS-Academy-for-Beginners#7]
老师您好，我在跟随您的课程使用Gazebo进行仿真时，到开启键盘控制机器人都没有问题，等到运行：
`rosrun image_view image_view image:=/camera/rgb/image_raw`时，就会出现机器人摄像头视角的画面一闪就关闭，错误提示为：ASSERT:false in file qasciikey.cpp,line495
请问老师如何解决呢？

**Comment by x7hkvip** [comment]
问题补充，我已经升级gazebo为7.13.1版本了

**Comment by lazyparser** [comment]
@anchuanxu 看看帮助一下。

另外 @x7hkvip 后续问题也可以去 https://q.droid.ac.cn 问，老师们一般都挂在q站上。

**Comment by x7hkvip** [comment]
@lazyparser 在尝试重新编译并刷新环境后问题已解决。另外已向罗校长发送了申请注册邮件，感谢您的帮助

**Comment by anchuanxu** [comment]
nice
