### ISSUE TITLE
安装依赖后,编译时报错

### ISSUE THREAD

**Issue by jnb105** [DroidAITech/ROS-Academy-for-Beginners#8]
CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by
  "controller_manager" with any of the following names:

    controller_managerConfig.cmake
    controller_manager-config.cmake

 -- Could not find the required component 'controller_manager'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by
  "controller_manager" with any of the following names:

    controller_managerConfig.cmake
    controller_manager-config.cmake
 Add the installation prefix of "controller_manager" to CMAKE_PREFIX_PATH or
  set "controller_manager_DIR" to a directory containing one of the above
  files.  If "controller_manager" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  ROS-Academy-for-Beginners/navigation_sim_demo/CMakeLists.txt:3 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/zju/catkin_test/build/CMakeFiles/CMakeOutput.log".
See also "/home/zju/catkin_test/build/CMakeFiles/CMakeError.log".
Makefile:682: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 1
Invoking "make cmake_check_build_system" failed

**Comment by jnb105** [comment]
补充：老师我是慕课学习者。现在按照你的课件练习。碰到问题，不知道怎么解决，求帮助。。 @wuyanjun @sychaichangkun

**Comment by lazyparser** [comment]
"controller_manager" 这个依赖关系安装了么？

另外 @jnb105  后续问题也可以去 https://q.droid.ac.cn 问，老师们一般都挂在q站上。

**Comment by anchuanxu** [comment]
安装 ''controller_manager”依赖，可以 git clone https://github.com/ros-controls/ros_control.git -b jade_devel

**Comment by anchuanxu** [comment]
尝试安装"controller_manager" 可以git clone https://github.com/ros-controls/ros_control.git -b kinetic_devel 如果没用参考https://github.com/cvra/roscvra/issues/4，欢迎来机器人开发者社区 https://q.droid.ac.cn提问

**Comment by lazyparser** [comment]
关闭没有后续反馈的 issues
