### ISSUE TITLE
laser数据都是inf

### ISSUE THREAD

**Issue by SehunKing** [DroidAITech/ROS-Academy-for-Beginners#81]
老师您好，我运行gazebo模型和机器人移动都没有问题，但rviz查看laser数据时选择了/scan话题，却没有红点出现，而查看其他传感器如camera数据都正常，echo /scan发现数据都是inf，请问如何解决呢？

环境是常规ubuntu16

**Comment by anchuanxu** [comment]
### 如果出现这种问题，是gazebo插件的问题

修改步骤：

`robot_sim_demo/urdf/sick_time.urdf.xacro` 文件第76行注释掉，换成77行，同时98行注释掉，换成99行。替换该插件为无gpu版本即可。

**Comment by anchuanxu** [comment]
造成该问题的原因是1，机器没有独立显卡。2独立显卡驱动没有安装完成。
